# =============================================================================
# LOD 300 Structural Model — Auto-Generated by PDF-to-SketchUp Pipeline
# Model: gemini-2.5-flash  |  DO NOT EDIT — regenerate from mapped_members.json
# =============================================================================

model  = Sketchup.active_model
model.name        = "LOD300 Structural Model"
model.description = "Generated by PDF-to-SketchUp pipeline"
ents   = model.active_entities
layers = model.layers
model.start_operation('LOD300 Structural Import', true)

def get_or_create_layer(layers, name)
  layers[name] || layers.add(name)
end

# ── Layers ────────────────────────────────────────────────────────────────────
["STR-Columns", "STR-Beams", "STR-Braces", "STR-Plates",
 "STR-Foundations", "STR-Slabs", "LOD300_UNMAPPED_NEEDS_REVIEW"].each do |lname|
  get_or_create_layer(layers, lname)
end

# ── Materials ─────────────────────────────────────────────────────────────────
_mats = model.materials
_steel_mat = _mats["Structural_Steel"] || _mats.add("Structural_Steel")
_steel_mat.color = Sketchup::Color.new(160, 160, 175)
_concrete_mat = _mats["Concrete"] || _mats.add("Concrete")
_concrete_mat.color = Sketchup::Color.new(180, 175, 165)


# ---- CH13c | CH13c | other ----
begin
  _sp  = Geom::Point3d.new(0.mm, 0.mm, 3500.mm)
  _ep  = Geom::Point3d.new(4200.mm, 0.mm, 3500.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP CH13c: zero-length (check mapper coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[0, 0], [65, 0], [65, 125], [0, 125]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = get_or_create_layer(layers, "STR-Beams")
    _grp.material = _steel_mat
    _grp.set_attribute("IFC", "Mark",    "CH13c")
    _grp.set_attribute("IFC", "Section", "CH13c")
    _grp.set_attribute("IFC", "Type",    "other")
    _grp.name = "CH13c"
  end
rescue => e
  puts "SKIP CH13c: #{e.message}"
end

# ---- FB | FB | other ----
begin
  _sp  = Geom::Point3d.new(0.mm, 0.mm, 10500.mm)
  _ep  = Geom::Point3d.new(4200.mm, 0.mm, 10500.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP FB: zero-length (check mapper coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[0, 0], [100, 0], [100, 10], [0, 10]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = get_or_create_layer(layers, "STR-Beams")
    _grp.material = _steel_mat
    _grp.set_attribute("IFC", "Mark",    "FB")
    _grp.set_attribute("IFC", "Section", "FB")
    _grp.set_attribute("IFC", "Type",    "other")
    _grp.name = "FB"
  end
rescue => e
  puts "SKIP FB: #{e.message}"
end

# ---- UB36b | UB36b | beam ----
begin
  _sp  = Geom::Point3d.new(0.mm, 11525.mm, 10500.mm)
  _ep  = Geom::Point3d.new(0.mm, 17438.mm, 10500.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP UB36b: zero-length (check mapper coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[-86, 0], [86, 0], [86, 359], [-86, 359]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = get_or_create_layer(layers, "STR-Beams")
    _grp.material = _steel_mat
    _grp.set_attribute("IFC", "Mark",    "UB36b")
    _grp.set_attribute("IFC", "Section", "UB36b")
    _grp.set_attribute("IFC", "Type",    "beam")
    _grp.name = "UB36b"
  end
rescue => e
  puts "SKIP UB36b: #{e.message}"
end

# ---- PF20a | PF20a | other ----
begin
  _sp  = Geom::Point3d.new(0.mm, 5762.mm, 3500.mm)
  _ep  = Geom::Point3d.new(4200.mm, 5762.mm, 3500.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP PF20a: zero-length (check mapper coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[-25, 0], [25, 0], [25, 20], [-25, 20]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = get_or_create_layer(layers, "STR-Beams")
    _grp.material = _steel_mat
    _grp.set_attribute("IFC", "Mark",    "PF20a")
    _grp.set_attribute("IFC", "Section", "PF20a")
    _grp.set_attribute("IFC", "Type",    "other")
    _grp.name = "PF20a"
  end
rescue => e
  puts "SKIP PF20a: #{e.message}"
end

# ---- CH*35c | CH*35c | other ----
begin
  _sp  = Geom::Point3d.new(0.mm, 11525.mm, 3500.mm)
  _ep  = Geom::Point3d.new(4200.mm, 11525.mm, 3500.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP CH*35c: zero-length (check mapper coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[-25, 0], [25, 0], [25, 35], [-25, 35]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = get_or_create_layer(layers, "STR-Beams")
    _grp.material = _steel_mat
    _grp.set_attribute("IFC", "Mark",    "CH*35c")
    _grp.set_attribute("IFC", "Section", "CH*35c")
    _grp.set_attribute("IFC", "Type",    "other")
    _grp.name = "CH*35c"
  end
rescue => e
  puts "SKIP CH*35c: #{e.message}"
end

# ---- CH40b | CH40b | other ----
begin
  _sp  = Geom::Point3d.new(0.mm, 17438.mm, 10500.mm)
  _ep  = Geom::Point3d.new(4200.mm, 17438.mm, 10500.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP CH40b: zero-length (check mapper coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[0, 0], [100, 0], [100, 400], [0, 400]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = get_or_create_layer(layers, "STR-Beams")
    _grp.material = _steel_mat
    _grp.set_attribute("IFC", "Mark",    "CH40b")
    _grp.set_attribute("IFC", "Section", "CH40b")
    _grp.set_attribute("IFC", "Type",    "other")
    _grp.name = "CH40b"
  end
rescue => e
  puts "SKIP CH40b: #{e.message}"
end

# ---- SH30b | SH30b | other ----
begin
  _sp  = Geom::Point3d.new(0.mm, 17438.mm, 10500.mm)
  _ep  = Geom::Point3d.new(4200.mm, 17438.mm, 10500.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP SH30b: zero-length (check mapper coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[-50, -150], [50, -150], [50, 150], [-50, 150]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = get_or_create_layer(layers, "STR-Beams")
    _grp.material = _steel_mat
    _grp.set_attribute("IFC", "Mark",    "SH30b")
    _grp.set_attribute("IFC", "Section", "SH30b")
    _grp.set_attribute("IFC", "Type",    "other")
    _grp.name = "SH30b"
  end
rescue => e
  puts "SKIP SH30b: #{e.message}"
end

# ---- CH32a | CH32a | other ----
begin
  _sp  = Geom::Point3d.new(4200.mm, 5762.mm, 3500.mm)
  _ep  = Geom::Point3d.new(9150.mm, 5762.mm, 3500.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP CH32a: zero-length (check mapper coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[0, 0], [80, 0], [80, 320], [0, 320]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = get_or_create_layer(layers, "STR-Beams")
    _grp.material = _steel_mat
    _grp.set_attribute("IFC", "Mark",    "CH32a")
    _grp.set_attribute("IFC", "Section", "CH32a")
    _grp.set_attribute("IFC", "Type",    "other")
    _grp.name = "CH32a"
  end
rescue => e
  puts "SKIP CH32a: #{e.message}"
end

# ---- PF25a | PF25a | other ----
begin
  _sp  = Geom::Point3d.new(0.mm, 0.mm, 3500.mm)
  _ep  = Geom::Point3d.new(4200.mm, 0.mm, 3500.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP PF25a: zero-length (check mapper coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[-25, 0], [25, 0], [25, 25], [-25, 25]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = get_or_create_layer(layers, "STR-Beams")
    _grp.material = _steel_mat
    _grp.set_attribute("IFC", "Mark",    "PF25a")
    _grp.set_attribute("IFC", "Section", "PF25a")
    _grp.set_attribute("IFC", "Type",    "other")
    _grp.name = "PF25a"
  end
rescue => e
  puts "SKIP PF25a: #{e.message}"
end

# ---- CH 35a |  | other ----
begin
  _sp  = Geom::Point3d.new(0.mm, 0.mm, 3500.mm)
  _ep  = Geom::Point3d.new(4200.mm, 0.mm, 3500.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP CH 35a: zero-length (check mapper coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[-25, 0], [25, 0], [25, 100], [-25, 100]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = get_or_create_layer(layers, "STR-Beams")
    _grp.material = _steel_mat
    _grp.set_attribute("IFC", "Mark",    "CH 35a")
    _grp.set_attribute("IFC", "Section", "")
    _grp.set_attribute("IFC", "Type",    "other")
    _grp.name = "CH 35a"
  end
rescue => e
  puts "SKIP CH 35a: #{e.message}"
end

# ---- C 1 |  | column ----
begin
  _sp  = Geom::Point3d.new(0.mm, 0.mm, 10500.mm)
  _ep  = Geom::Point3d.new(0.mm, 0.mm, 13500.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP C 1: zero-length (check mapper coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[-50, 0], [50, 0], [50, 100], [-50, 100]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = get_or_create_layer(layers, "STR-Columns")
    _grp.material = _steel_mat
    _grp.set_attribute("IFC", "Mark",    "C 1")
    _grp.set_attribute("IFC", "Section", "")
    _grp.set_attribute("IFC", "Type",    "column")
    _grp.name = "C 1"
  end
rescue => e
  puts "SKIP C 1: #{e.message}"
end

# ---- C 2 |  | column ----
begin
  _sp  = Geom::Point3d.new(4200.mm, 0.mm, 10500.mm)
  _ep  = Geom::Point3d.new(4200.mm, 0.mm, 13500.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP C 2: zero-length (check mapper coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[-50, 0], [50, 0], [50, 100], [-50, 100]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = get_or_create_layer(layers, "STR-Columns")
    _grp.material = _steel_mat
    _grp.set_attribute("IFC", "Mark",    "C 2")
    _grp.set_attribute("IFC", "Section", "")
    _grp.set_attribute("IFC", "Type",    "column")
    _grp.name = "C 2"
  end
rescue => e
  puts "SKIP C 2: #{e.message}"
end

# ---- C 3 |  | column ----
begin
  _sp  = Geom::Point3d.new(9150.mm, 0.mm, 10500.mm)
  _ep  = Geom::Point3d.new(9150.mm, 0.mm, 13500.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP C 3: zero-length (check mapper coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[-50, 0], [50, 0], [50, 100], [-50, 100]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = get_or_create_layer(layers, "STR-Columns")
    _grp.material = _steel_mat
    _grp.set_attribute("IFC", "Mark",    "C 3")
    _grp.set_attribute("IFC", "Section", "")
    _grp.set_attribute("IFC", "Type",    "column")
    _grp.name = "C 3"
  end
rescue => e
  puts "SKIP C 3: #{e.message}"
end

# ---- C 4 |  | column ----
begin
  _sp  = Geom::Point3d.new(13350.mm, 0.mm, 10500.mm)
  _ep  = Geom::Point3d.new(13350.mm, 0.mm, 13500.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP C 4: zero-length (check mapper coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[-50, 0], [50, 0], [50, 100], [-50, 100]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = get_or_create_layer(layers, "STR-Columns")
    _grp.material = _steel_mat
    _grp.set_attribute("IFC", "Mark",    "C 4")
    _grp.set_attribute("IFC", "Section", "")
    _grp.set_attribute("IFC", "Type",    "column")
    _grp.name = "C 4"
  end
rescue => e
  puts "SKIP C 4: #{e.message}"
end

# ---- C 5 |  | column ----
begin
  _sp  = Geom::Point3d.new(0.mm, 5762.mm, 10500.mm)
  _ep  = Geom::Point3d.new(0.mm, 5762.mm, 13500.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP C 5: zero-length (check mapper coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[-50, 0], [50, 0], [50, 100], [-50, 100]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = get_or_create_layer(layers, "STR-Columns")
    _grp.material = _steel_mat
    _grp.set_attribute("IFC", "Mark",    "C 5")
    _grp.set_attribute("IFC", "Section", "")
    _grp.set_attribute("IFC", "Type",    "column")
    _grp.name = "C 5"
  end
rescue => e
  puts "SKIP C 5: #{e.message}"
end

# ---- C 6 |  | column ----
begin
  _sp  = Geom::Point3d.new(4200.mm, 5762.mm, 10500.mm)
  _ep  = Geom::Point3d.new(4200.mm, 5762.mm, 13500.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP C 6: zero-length (check mapper coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[-50, 0], [50, 0], [50, 100], [-50, 100]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = get_or_create_layer(layers, "STR-Columns")
    _grp.material = _steel_mat
    _grp.set_attribute("IFC", "Mark",    "C 6")
    _grp.set_attribute("IFC", "Section", "")
    _grp.set_attribute("IFC", "Type",    "column")
    _grp.name = "C 6"
  end
rescue => e
  puts "SKIP C 6: #{e.message}"
end

# ---- C 7 |  | column ----
begin
  _sp  = Geom::Point3d.new(9150.mm, 5762.mm, 10500.mm)
  _ep  = Geom::Point3d.new(9150.mm, 5762.mm, 13500.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP C 7: zero-length (check mapper coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[-50, 0], [50, 0], [50, 100], [-50, 100]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = get_or_create_layer(layers, "STR-Columns")
    _grp.material = _steel_mat
    _grp.set_attribute("IFC", "Mark",    "C 7")
    _grp.set_attribute("IFC", "Section", "")
    _grp.set_attribute("IFC", "Type",    "column")
    _grp.name = "C 7"
  end
rescue => e
  puts "SKIP C 7: #{e.message}"
end

# ---- C 8 |  | column ----
begin
  _sp  = Geom::Point3d.new(13350.mm, 5762.mm, 10500.mm)
  _ep  = Geom::Point3d.new(13350.mm, 5762.mm, 13500.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP C 8: zero-length (check mapper coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[-50, 0], [50, 0], [50, 100], [-50, 100]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = get_or_create_layer(layers, "STR-Columns")
    _grp.material = _steel_mat
    _grp.set_attribute("IFC", "Mark",    "C 8")
    _grp.set_attribute("IFC", "Section", "")
    _grp.set_attribute("IFC", "Type",    "column")
    _grp.name = "C 8"
  end
rescue => e
  puts "SKIP C 8: #{e.message}"
end

# ---- C 12 | CH400 | column ----
begin
  _sp  = Geom::Point3d.new(13350.mm, 11525.mm, 10500.mm)
  _ep  = Geom::Point3d.new(13350.mm, 11525.mm, 13500.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP C 12: zero-length (check mapper coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[0, 0], [1000, 0], [1000, 4000], [0, 4000]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = get_or_create_layer(layers, "STR-Columns")
    _grp.material = _steel_mat
    _grp.set_attribute("IFC", "Mark",    "C 12")
    _grp.set_attribute("IFC", "Section", "CH400")
    _grp.set_attribute("IFC", "Type",    "column")
    _grp.name = "C 12"
  end
rescue => e
  puts "SKIP C 12: #{e.message}"
end

# ---- CH* 35c | CH400 | other ----
begin
  _sp  = Geom::Point3d.new(0.mm, 0.mm, 10500.mm)
  _ep  = Geom::Point3d.new(4200.mm, 0.mm, 10500.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP CH* 35c: zero-length (check mapper coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[0, 0], [1000, 0], [1000, 4000], [0, 4000]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = get_or_create_layer(layers, "STR-Beams")
    _grp.material = _steel_mat
    _grp.set_attribute("IFC", "Mark",    "CH* 35c")
    _grp.set_attribute("IFC", "Section", "CH400")
    _grp.set_attribute("IFC", "Type",    "other")
    _grp.name = "CH* 35c"
  end
rescue => e
  puts "SKIP CH* 35c: #{e.message}"
end

# ---- STAIR 04 |  | other ----
begin
  _sp  = Geom::Point3d.new(0.mm, 11525.mm, 10500.mm)
  _ep  = Geom::Point3d.new(0.mm, 17438.mm, 10500.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP STAIR 04: zero-length (check mapper coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[-25, 0], [25, 0], [25, 100], [-25, 100]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = get_or_create_layer(layers, "STR-Beams")
    _grp.material = _steel_mat
    _grp.set_attribute("IFC", "Mark",    "STAIR 04")
    _grp.set_attribute("IFC", "Section", "")
    _grp.set_attribute("IFC", "Type",    "other")
    _grp.name = "STAIR 04"
  end
rescue => e
  puts "SKIP STAIR 04: #{e.message}"
end

# ---- STAIR 03 |  | other ----
begin
  _sp  = Geom::Point3d.new(4200.mm, 5762.mm, 3500.mm)
  _ep  = Geom::Point3d.new(4200.mm, 11525.mm, 3500.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP STAIR 03: zero-length (check mapper coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[-25, 0], [25, 0], [25, 100], [-25, 100]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = get_or_create_layer(layers, "STR-Beams")
    _grp.material = _steel_mat
    _grp.set_attribute("IFC", "Mark",    "STAIR 03")
    _grp.set_attribute("IFC", "Section", "")
    _grp.set_attribute("IFC", "Type",    "other")
    _grp.name = "STAIR 03"
  end
rescue => e
  puts "SKIP STAIR 03: #{e.message}"
end

# ---- STAIR 02 |  | other ----
begin
  _sp  = Geom::Point3d.new(9150.mm, 5762.mm, 3500.mm)
  _ep  = Geom::Point3d.new(9150.mm, 11525.mm, 3500.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP STAIR 02: zero-length (check mapper coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[-25, 0], [25, 0], [25, 100], [-25, 100]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = get_or_create_layer(layers, "STR-Beams")
    _grp.material = _steel_mat
    _grp.set_attribute("IFC", "Mark",    "STAIR 02")
    _grp.set_attribute("IFC", "Section", "")
    _grp.set_attribute("IFC", "Type",    "other")
    _grp.name = "STAIR 02"
  end
rescue => e
  puts "SKIP STAIR 02: #{e.message}"
end

# ---- C 10 | CH400 | column ----
begin
  _sp  = Geom::Point3d.new(4200.mm, 11525.mm, 10500.mm)
  _ep  = Geom::Point3d.new(4200.mm, 11525.mm, 13500.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP C 10: zero-length (check mapper coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[0, 0], [1000, 0], [1000, 4000], [0, 4000]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = get_or_create_layer(layers, "STR-Columns")
    _grp.material = _steel_mat
    _grp.set_attribute("IFC", "Mark",    "C 10")
    _grp.set_attribute("IFC", "Section", "CH400")
    _grp.set_attribute("IFC", "Type",    "column")
    _grp.name = "C 10"
  end
rescue => e
  puts "SKIP C 10: #{e.message}"
end

# ---- C 11 | FB400 | column ----
begin
  _sp  = Geom::Point3d.new(9150.mm, 11525.mm, 10500.mm)
  _ep  = Geom::Point3d.new(9150.mm, 11525.mm, 13500.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP C 11: zero-length (check mapper coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[-200, 0], [200, 0], [200, 400], [-200, 400]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = get_or_create_layer(layers, "STR-Columns")
    _grp.material = _steel_mat
    _grp.set_attribute("IFC", "Mark",    "C 11")
    _grp.set_attribute("IFC", "Section", "FB400")
    _grp.set_attribute("IFC", "Type",    "column")
    _grp.name = "C 11"
  end
rescue => e
  puts "SKIP C 11: #{e.message}"
end

# ---- STAIR 0 |  | other ----
begin
  _sp  = Geom::Point3d.new(0.mm, 0.mm, 0.mm)
  _ep  = Geom::Point3d.new(0.mm, 0.mm, 3500.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP STAIR 0: zero-length (check mapper coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[-25, 0], [25, 0], [25, 100], [-25, 100]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = get_or_create_layer(layers, "STR-Beams")
    _grp.material = _steel_mat
    _grp.set_attribute("IFC", "Mark",    "STAIR 0")
    _grp.set_attribute("IFC", "Section", "")
    _grp.set_attribute("IFC", "Type",    "other")
    _grp.name = "STAIR 0"
  end
rescue => e
  puts "SKIP STAIR 0: #{e.message}"
end

# ---- C 13 | CH400 | column ----
begin
  _sp  = Geom::Point3d.new(0.mm, 17438.mm, 10500.mm)
  _ep  = Geom::Point3d.new(0.mm, 17438.mm, 13500.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP C 13: zero-length (check mapper coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[0, 0], [1000, 0], [1000, 4000], [0, 4000]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = get_or_create_layer(layers, "STR-Columns")
    _grp.material = _steel_mat
    _grp.set_attribute("IFC", "Mark",    "C 13")
    _grp.set_attribute("IFC", "Section", "CH400")
    _grp.set_attribute("IFC", "Type",    "column")
    _grp.name = "C 13"
  end
rescue => e
  puts "SKIP C 13: #{e.message}"
end

# ---- C 14 | CH400 | column ----
begin
  _sp  = Geom::Point3d.new(4200.mm, 17438.mm, 10500.mm)
  _ep  = Geom::Point3d.new(4200.mm, 17438.mm, 13500.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP C 14: zero-length (check mapper coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[0, 0], [1000, 0], [1000, 4000], [0, 4000]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = get_or_create_layer(layers, "STR-Columns")
    _grp.material = _steel_mat
    _grp.set_attribute("IFC", "Mark",    "C 14")
    _grp.set_attribute("IFC", "Section", "CH400")
    _grp.set_attribute("IFC", "Type",    "column")
    _grp.name = "C 14"
  end
rescue => e
  puts "SKIP C 14: #{e.message}"
end

# ---- C 15 |  | column ----
begin
  _sp  = Geom::Point3d.new(9150.mm, 17438.mm, 10500.mm)
  _ep  = Geom::Point3d.new(9150.mm, 17438.mm, 13500.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP C 15: zero-length (check mapper coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[-50, 0], [50, 0], [50, 100], [-50, 100]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = get_or_create_layer(layers, "STR-Columns")
    _grp.material = _steel_mat
    _grp.set_attribute("IFC", "Mark",    "C 15")
    _grp.set_attribute("IFC", "Section", "")
    _grp.set_attribute("IFC", "Type",    "column")
    _grp.name = "C 15"
  end
rescue => e
  puts "SKIP C 15: #{e.message}"
end

# ---- C 16 |  | column ----
begin
  _sp  = Geom::Point3d.new(13350.mm, 17438.mm, 10500.mm)
  _ep  = Geom::Point3d.new(13350.mm, 17438.mm, 13500.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP C 16: zero-length (check mapper coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[-50, 0], [50, 0], [50, 100], [-50, 100]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = get_or_create_layer(layers, "STR-Columns")
    _grp.material = _steel_mat
    _grp.set_attribute("IFC", "Mark",    "C 16")
    _grp.set_attribute("IFC", "Section", "")
    _grp.set_attribute("IFC", "Type",    "column")
    _grp.name = "C 16"
  end
rescue => e
  puts "SKIP C 16: #{e.message}"
end

# ---- CH 35c | CH 35c | column ----
begin
  _sp  = Geom::Point3d.new(0.mm, 5762.mm, 10500.mm)
  _ep  = Geom::Point3d.new(0.mm, 5762.mm, 13500.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP CH 35c: zero-length (check mapper coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[0, 0], [87.5, 0], [87.5, 350], [0, 350]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = get_or_create_layer(layers, "STR-Columns")
    _grp.material = _steel_mat
    _grp.set_attribute("IFC", "Mark",    "CH 35c")
    _grp.set_attribute("IFC", "Section", "CH 35c")
    _grp.set_attribute("IFC", "Type",    "column")
    _grp.name = "CH 35c"
  end
rescue => e
  puts "SKIP CH 35c: #{e.message}"
end

# ---- UB20d | UB20d | beam ----
begin
  _sp  = Geom::Point3d.new(0.mm, 0.mm, 3500.mm)
  _ep  = Geom::Point3d.new(0.mm, 5762.mm, 3500.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP UB20d: zero-length (check mapper coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[-50, 0], [50, 0], [50, 200], [-50, 200]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = get_or_create_layer(layers, "STR-Beams")
    _grp.material = _steel_mat
    _grp.set_attribute("IFC", "Mark",    "UB20d")
    _grp.set_attribute("IFC", "Section", "UB20d")
    _grp.set_attribute("IFC", "Type",    "beam")
    _grp.name = "UB20d"
  end
rescue => e
  puts "SKIP UB20d: #{e.message}"
end

# ---- UB36c | UB36c | beam ----
begin
  _sp  = Geom::Point3d.new(0.mm, 0.mm, 3500.mm)
  _ep  = Geom::Point3d.new(0.mm, 5762.mm, 3500.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP UB36c: zero-length (check mapper coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[-90, 0], [90, 0], [90, 360], [-90, 360]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = get_or_create_layer(layers, "STR-Beams")
    _grp.material = _steel_mat
    _grp.set_attribute("IFC", "Mark",    "UB36c")
    _grp.set_attribute("IFC", "Section", "UB36c")
    _grp.set_attribute("IFC", "Type",    "beam")
    _grp.name = "UB36c"
  end
rescue => e
  puts "SKIP UB36c: #{e.message}"
end

# ---- 250PFC | 250PFC | beam ----
begin
  _sp  = Geom::Point3d.new(0.mm, 11525.mm, 3500.mm)
  _ep  = Geom::Point3d.new(4200.mm, 11525.mm, 3500.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP 250PFC: zero-length (check mapper coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[0, 0], [90, 0], [90, 250], [0, 250]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = get_or_create_layer(layers, "STR-Beams")
    _grp.material = _steel_mat
    _grp.set_attribute("IFC", "Mark",    "250PFC")
    _grp.set_attribute("IFC", "Section", "250PFC")
    _grp.set_attribute("IFC", "Type",    "beam")
    _grp.name = "250PFC"
  end
rescue => e
  puts "SKIP 250PFC: #{e.message}"
end

# ---- SH15a | SH15a | other ----
begin
  _sp  = Geom::Point3d.new(9150.mm, 5762.mm, 3500.mm)
  _ep  = Geom::Point3d.new(13350.mm, 5762.mm, 3500.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP SH15a: zero-length (check mapper coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[-25, 0], [25, 0], [25, 15], [-25, 15]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = get_or_create_layer(layers, "STR-Beams")
    _grp.material = _steel_mat
    _grp.set_attribute("IFC", "Mark",    "SH15a")
    _grp.set_attribute("IFC", "Section", "SH15a")
    _grp.set_attribute("IFC", "Type",    "other")
    _grp.name = "SH15a"
  end
rescue => e
  puts "SKIP SH15a: #{e.message}"
end

# ---- SH08d | SH08d | other ----
begin
  _sp  = Geom::Point3d.new(0.mm, 11525.mm, 10500.mm)
  _ep  = Geom::Point3d.new(0.mm, 11525.mm, 13500.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP SH08d: zero-length (check mapper coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[-44.5, -44.5], [44.5, -44.5], [44.5, 44.5], [-44.5, 44.5]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = get_or_create_layer(layers, "STR-Beams")
    _grp.material = _steel_mat
    _grp.set_attribute("IFC", "Mark",    "SH08d")
    _grp.set_attribute("IFC", "Section", "SH08d")
    _grp.set_attribute("IFC", "Type",    "other")
    _grp.name = "SH08d"
  end
rescue => e
  puts "SKIP SH08d: #{e.message}"
end

# ---- SH10f | SH10f | other ----
begin
  _sp  = Geom::Point3d.new(13350.mm, 5762.mm, 3500.mm)
  _ep  = Geom::Point3d.new(17550.mm, 5762.mm, 3500.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP SH10f: zero-length (check mapper coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[-25, 0], [25, 0], [25, 10], [-25, 10]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = get_or_create_layer(layers, "STR-Beams")
    _grp.material = _steel_mat
    _grp.set_attribute("IFC", "Mark",    "SH10f")
    _grp.set_attribute("IFC", "Section", "SH10f")
    _grp.set_attribute("IFC", "Type",    "other")
    _grp.name = "SH10f"
  end
rescue => e
  puts "SKIP SH10f: #{e.message}"
end

# ---- SH15b | SH15b | other ----
begin
  _sp  = Geom::Point3d.new(0.mm, 0.mm, 3500.mm)
  _ep  = Geom::Point3d.new(0.mm, 5762.mm, 3500.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP SH15b: zero-length (check mapper coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[-25, 0], [25, 0], [25, 15], [-25, 15]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = get_or_create_layer(layers, "STR-Beams")
    _grp.material = _steel_mat
    _grp.set_attribute("IFC", "Mark",    "SH15b")
    _grp.set_attribute("IFC", "Section", "SH15b")
    _grp.set_attribute("IFC", "Type",    "other")
    _grp.name = "SH15b"
  end
rescue => e
  puts "SKIP SH15b: #{e.message}"
end

# ---- SH10e | SH10e | beam ----
begin
  _sp  = Geom::Point3d.new(0.mm, 0.mm, 3500.mm)
  _ep  = Geom::Point3d.new(4200.mm, 0.mm, 3500.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP SH10e: zero-length (check mapper coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[-25, 0], [25, 0], [25, 10], [-25, 10]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = get_or_create_layer(layers, "STR-Beams")
    _grp.material = _steel_mat
    _grp.set_attribute("IFC", "Mark",    "SH10e")
    _grp.set_attribute("IFC", "Section", "SH10e")
    _grp.set_attribute("IFC", "Type",    "beam")
    _grp.name = "SH10e"
  end
rescue => e
  puts "SKIP SH10e: #{e.message}"
end

# ---- UA15a | UA15a | angle ----
begin
  _sp  = Geom::Point3d.new(4200.mm, 0.mm, 0.mm)
  _ep  = Geom::Point3d.new(4200.mm, 0.mm, 3500.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP UA15a: zero-length (check mapper coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[-25, 0], [25, 0], [25, 15], [-25, 15]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = get_or_create_layer(layers, "STR-Beams")
    _grp.material = _steel_mat
    _grp.set_attribute("IFC", "Mark",    "UA15a")
    _grp.set_attribute("IFC", "Section", "UA15a")
    _grp.set_attribute("IFC", "Type",    "angle")
    _grp.name = "UA15a"
  end
rescue => e
  puts "SKIP UA15a: #{e.message}"
end

# ---- SH150 | SH150 | other ----
begin
  _sp  = Geom::Point3d.new(4200.mm, 5762.mm, 3500.mm)
  _ep  = Geom::Point3d.new(9150.mm, 5762.mm, 3500.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP SH150: zero-length (check mapper coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[-37.5, 0], [37.5, 0], [37.5, 150], [-37.5, 150]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = get_or_create_layer(layers, "STR-Beams")
    _grp.material = _steel_mat
    _grp.set_attribute("IFC", "Mark",    "SH150")
    _grp.set_attribute("IFC", "Section", "SH150")
    _grp.set_attribute("IFC", "Type",    "other")
    _grp.name = "SH150"
  end
rescue => e
  puts "SKIP SH150: #{e.message}"
end

# ---- CH35a | CH35a | column ----
begin
  _sp  = Geom::Point3d.new(0.mm, 0.mm, 0.mm)
  _ep  = Geom::Point3d.new(0.mm, 0.mm, 13500.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP CH35a: zero-length (check mapper coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[0, 0], [100, 0], [100, 380], [0, 380]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = get_or_create_layer(layers, "STR-Columns")
    _grp.material = _steel_mat
    _grp.set_attribute("IFC", "Mark",    "CH35a")
    _grp.set_attribute("IFC", "Section", "CH35a")
    _grp.set_attribute("IFC", "Type",    "column")
    _grp.name = "CH35a"
  end
rescue => e
  puts "SKIP CH35a: #{e.message}"
end

# ---- EA15a | EA15a | angle ----
begin
  _sp  = Geom::Point3d.new(9150.mm, 0.mm, 0.mm)
  _ep  = Geom::Point3d.new(9150.mm, 0.mm, 3500.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP EA15a: zero-length (check mapper coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[-25, 0], [25, 0], [25, 15], [-25, 15]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = get_or_create_layer(layers, "STR-Beams")
    _grp.material = _steel_mat
    _grp.set_attribute("IFC", "Mark",    "EA15a")
    _grp.set_attribute("IFC", "Section", "EA15a")
    _grp.set_attribute("IFC", "Type",    "angle")
    _grp.name = "EA15a"
  end
rescue => e
  puts "SKIP EA15a: #{e.message}"
end

# ---- RH25b | RH25b | other ----
begin
  _sp  = Geom::Point3d.new(13350.mm, 0.mm, 0.mm)
  _ep  = Geom::Point3d.new(13350.mm, 0.mm, 3500.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP RH25b: zero-length (check mapper coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[-25, 0], [25, 0], [25, 25], [-25, 25]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = get_or_create_layer(layers, "STR-Beams")
    _grp.material = _steel_mat
    _grp.set_attribute("IFC", "Mark",    "RH25b")
    _grp.set_attribute("IFC", "Section", "RH25b")
    _grp.set_attribute("IFC", "Type",    "other")
    _grp.name = "RH25b"
  end
rescue => e
  puts "SKIP RH25b: #{e.message}"
end

# ---- UB20a | UB20a | beam ----
begin
  _sp  = Geom::Point3d.new(9150.mm, 5762.mm, 3500.mm)
  _ep  = Geom::Point3d.new(13350.mm, 5762.mm, 3500.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP UB20a: zero-length (check mapper coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[-66.5, 0], [66.5, 0], [66.5, 203], [-66.5, 203]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = get_or_create_layer(layers, "STR-Beams")
    _grp.material = _steel_mat
    _grp.set_attribute("IFC", "Mark",    "UB20a")
    _grp.set_attribute("IFC", "Section", "UB20a")
    _grp.set_attribute("IFC", "Type",    "beam")
    _grp.name = "UB20a"
  end
rescue => e
  puts "SKIP UB20a: #{e.message}"
end

# ---- SH10d | SH10d | other ----
begin
  _sp  = Geom::Point3d.new(0.mm, 11525.mm, 3500.mm)
  _ep  = Geom::Point3d.new(4200.mm, 11525.mm, 3500.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP SH10d: zero-length (check mapper coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[-25, 0], [25, 0], [25, 10], [-25, 10]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = get_or_create_layer(layers, "STR-Beams")
    _grp.material = _steel_mat
    _grp.set_attribute("IFC", "Mark",    "SH10d")
    _grp.set_attribute("IFC", "Section", "SH10d")
    _grp.set_attribute("IFC", "Type",    "other")
    _grp.name = "SH10d"
  end
rescue => e
  puts "SKIP SH10d: #{e.message}"
end

# ---- SH20a | SH20a | other ----
begin
  _sp  = Geom::Point3d.new(4200.mm, 11525.mm, 3500.mm)
  _ep  = Geom::Point3d.new(9150.mm, 11525.mm, 3500.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP SH20a: zero-length (check mapper coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[-37.5, -100], [37.5, -100], [37.5, 100], [-37.5, 100]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = get_or_create_layer(layers, "STR-Beams")
    _grp.material = _steel_mat
    _grp.set_attribute("IFC", "Mark",    "SH20a")
    _grp.set_attribute("IFC", "Section", "SH20a")
    _grp.set_attribute("IFC", "Type",    "other")
    _grp.name = "SH20a"
  end
rescue => e
  puts "SKIP SH20a: #{e.message}"
end

# ---- PF15a | PF15a | other ----
begin
  _sp  = Geom::Point3d.new(9150.mm, 11525.mm, 3500.mm)
  _ep  = Geom::Point3d.new(13350.mm, 11525.mm, 3500.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  if _len < 1.mm || !_vec.valid?
    puts "SKIP PF15a: zero-length (check mapper coords)"
  else
    _grp = ents.add_group
    _ge  = _grp.entities
    _t   = Geom::Transformation.new(_sp, _vec)
    _raw = [[-25, 0], [25, 0], [25, 15], [-25, 15]]
    _face = _ge.add_face(_raw.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
    _face.pushpull(_len) if _face
    _grp.layer = get_or_create_layer(layers, "STR-Beams")
    _grp.material = _steel_mat
    _grp.set_attribute("IFC", "Mark",    "PF15a")
    _grp.set_attribute("IFC", "Section", "PF15a")
    _grp.set_attribute("IFC", "Type",    "other")
    _grp.name = "PF15a"
  end
rescue => e
  puts "SKIP PF15a: #{e.message}"
end


model.commit_operation
puts "=== LOD 300 Import Complete ==="

# Auto-save model as .skp alongside this script
_skp_path = File.expand_path(File.join(File.dirname(__FILE__), 'lod300_model.skp'))
_saved = Sketchup.active_model.save(_skp_path)
puts _saved ? "Model saved: #{_skp_path}" : "Save FAILED: #{_skp_path}"
