"""
Agent 5 — Ruby Coder (upgraded)
Phase 5: Generate LOD 300 SketchUp Ruby script from 3D-mapped members.

For each member with start_point + end_point + rotation_degrees:
  1. Compute extrusion vector
  2. Build cross-section face on a plane perpendicular to the vector
  3. Rotate face by rotation_degrees
  4. PushPull by member length
  5. Tag with IFC attributes + correct layer

Unmapped members (confidence="unmapped") go to layer LOD300_UNMAPPED_NEEDS_REVIEW.
"""

import json
from pathlib import Path
from rich import print as rprint

from config import MAPPED_OUTPUT_FILE, CODER_OUTPUT_FILE
from core.llm_wrapper import call_llm, call_llm_with_feedback


RUBY_HEADER = """\
# =============================================================================
# LOD 300 Structural Model — Auto-Generated by PDF-to-SketchUp Pipeline
# Model: gemini-2.5-flash  |  DO NOT EDIT — regenerate from mapped_members.json
# =============================================================================

model  = Sketchup.active_model
model.name        = "LOD300 Structural Model"
model.description = "Generated by PDF-to-SketchUp pipeline"
ents   = model.active_entities
layers = model.layers
model.start_operation('LOD300 Structural Import', true)

def get_or_create_layer(layers, name)
  layers[name] || layers.add(name)
end

"""

RUBY_FOOTER = """\

model.commit_operation
puts "=== LOD 300 Import Complete ==="

# Auto-save model as .skp alongside this script
_skp_path = File.expand_path(File.join(File.dirname(__FILE__), 'lod300_model.skp'))
_saved = Sketchup.active_model.save(_skp_path)
puts _saved ? "Model saved: #{_skp_path}" : "Save FAILED: #{_skp_path}"
"""


CODER_PROMPT = """You are an Expert SketchUp Ruby API Developer generating LOD 300 structural elements.

Member data (JSON):
{member_json}

Write Ruby code that PRECISELY places this member in 3D space.

STRICT RULES — follow every one or the script will fail:
1. All dimensions in SketchUp inches. Convert mm with `.mm` suffix (e.g. `6000.mm`).
2. Compute start and end:
   start_pt = Geom::Point3d.new({sx}.mm, {sy}.mm, {sz}.mm)
   end_pt   = Geom::Point3d.new({ex}.mm, {ey}.mm, {ez}.mm)
3. Extrusion vector:
   vec = start_pt.vector_to(end_pt)
   length = start_pt.distance(end_pt)
4. Create a local group:
   grp = ents.add_group
   g_ents = grp.entities
5. Build the 2D cross-section face AT start_pt on a plane NORMAL to `vec`:
   - I/UB/UC sections: draw top flange, web, bottom flange as one closed polygon.
     Use actual flange width (bf), web height (d - 2*tf), flange thickness (tf), web thickness (tw).
     Parse these from the section string. If unknown, use proportional defaults:
     d = section_depth, bf = d*0.5, tf = d*0.06, tw = d*0.03.
   - RHS/SHS: outer rect minus inner rect (draw solid, SketchUp will show as box; note hollow).
   - CHS: 24-sided polygon approximation using Math::PI and radius.
   - PL/FB: simple rectangle (width x thickness).
   Use `Geom::Transformation.new` with a local coordinate system aligned to `vec`.
   Transform face points into world space before drawing.
6. Get the face: `face = g_ents.grep(Sketchup::Face).first`
7. Extrude: `face.pushpull(length)` (SketchUp's pushpull takes internal units — already in inches from step 1+3).
8. Layer assignment:
   layer_name = {layer_name}
   grp.layer = get_or_create_layer(layers, layer_name)
9. IFC attributes:
   grp.set_attribute("IFC", "Mark",    "{mark}")
   grp.set_attribute("IFC", "Section", "{section}")
   grp.set_attribute("IFC", "Type",    "{type}")
10. Name the group: `grp.name = "{mark}"`

Output ONLY valid Ruby code. No markdown, no prose, no method definitions outside the snippet."""


BATCH_CODER_PROMPT = """You are an Expert SketchUp Ruby API Developer generating LOD 300 structural elements.

MEMBER BATCH (JSON array of {count} members):
{members_json}

Write Ruby code that places EVERY member in 3D space. For each member output a section in this exact format:
  # ---- <mark> | <section> | <type> ----
  <ruby code for that member>

Use the outer-scope variables: `model`, `ents`, `layers`, `get_or_create_layer`.

STRICT RULES for EVERY member:
1. All dimensions in SketchUp inches — convert mm with `.mm` suffix (e.g. `6000.mm`).
2. start_pt = Geom::Point3d.new(start_point.x.mm, start_point.y.mm, start_point.z.mm)
   end_pt   = Geom::Point3d.new(end_point.x.mm,   end_point.y.mm,   end_point.z.mm)
3. vec = start_pt.vector_to(end_pt); length = start_pt.distance(end_pt)
4. grp = ents.add_group; g_ents = grp.entities
5. Cross-section face at start_pt on plane NORMAL to vec:
   - I/UB/UC: top flange + web + bottom flange polygon. Parse bf/d/tf/tw from section string;
     defaults: bf=d*0.5, tf=d*0.06, tw=d*0.03.
   - RHS/SHS: solid rectangle (hollow is visual-only in SketchUp).
   - CHS: 24-sided polygon using Math::PI and outer radius.
   - PL/FB: simple rectangle (width x thickness).
   Build a Geom::Transformation with local axes aligned to vec; transform face pts to world space.
6. face = g_ents.grep(Sketchup::Face).first; face.pushpull(length)
7. layer_name = "LOD300_UNMAPPED_NEEDS_REVIEW" if confidence=="unmapped" else "LOD300_<TYPE_UPPER>"
   grp.layer = get_or_create_layer(layers, layer_name)
8. grp.set_attribute("IFC","Mark",<mark>); grp.set_attribute("IFC","Section",<section>)
   grp.set_attribute("IFC","Type",<type>); grp.name = <mark>

Output ONLY valid Ruby code for ALL {count} members. No markdown fences, no prose."""


def _fill_prompt(member: dict) -> str:
    sp      = member.get("start_point") or {"x": 0, "y": 0, "z": 0}
    ep      = member.get("end_point")   or {"x": 0, "y": 0, "z": 3000}
    mark    = member.get("mark")    or "M?"
    section = member.get("section") or "UB200x100x20"
    mtype   = member.get("type")    or "beam"
    conf    = member.get("confidence") or "high"
    layer_name = (
        "LOD300_UNMAPPED_NEEDS_REVIEW" if conf == "unmapped"
        else f"LOD300_{mtype.upper()}"
    )

    sx = str(sp.get("x") or 0); sy = str(sp.get("y") or 0); sz = str(sp.get("z") or 0)
    ex = str(ep.get("x") or 0); ey = str(ep.get("y") or 0); ez = str(ep.get("z") or 3000)

    return (
        CODER_PROMPT
        .replace("{member_json}", json.dumps(member, indent=2))
        .replace("{sx}", sx).replace("{sy}", sy).replace("{sz}", sz)
        .replace("{ex}", ex).replace("{ey}", ey).replace("{ez}", ez)
        .replace("{layer_name}", f'"{layer_name}"')
        .replace("{mark}", mark)
        .replace("{section}", section)
        .replace("{type}", mtype)
    )


def _fill_batch_prompt(batch: list[dict]) -> str:
    return (
        BATCH_CODER_PROMPT
        .replace("{count}", str(len(batch)))
        .replace("{members_json}", json.dumps(batch, indent=2))
    )


def generate_ruby_for_member(member: dict, error_feedback: str | None = None, previous_ruby: str | None = None) -> str:
    """Single-member call — used only for error-feedback retries."""
    prompt = _fill_prompt(member)
    if error_feedback and previous_ruby:
        return call_llm_with_feedback(prompt, error_feedback, previous_ruby)
    return call_llm(prompt)


def _generate_ruby_for_batch(batch: list[dict]) -> str:
    """Send one batch of members to the LLM, return raw Ruby text for the whole batch."""
    prompt = _fill_batch_prompt(batch)
    raw = call_llm(prompt)
    # Strip accidental markdown fences
    raw = raw.strip()
    if raw.startswith("```"):
        raw = raw.split("```", 1)[1]
        if raw.startswith("ruby"):
            raw = raw[4:]
        raw = raw.rsplit("```", 1)[0].strip()
    return raw


def build_ruby_script(mapped_members: list[dict], error_feedback_map: dict | None = None) -> str:
    """
    Build the full Ruby script using at most 3 batched LLM calls.
    error_feedback_map retries are still done per-member (single call) to keep diffs minimal.
    """
    error_feedback_map = error_feedback_map or {}
    total = len(mapped_members)

    # Split members needing error-retry out first; they get individual calls.
    retry_members  = [m for m in mapped_members if error_feedback_map.get(m.get("mark", ""))]
    batch_members  = [m for m in mapped_members if not error_feedback_map.get(m.get("mark", ""))]

    BATCH_SIZE = 30
    batches = [batch_members[i:i + BATCH_SIZE] for i in range(0, len(batch_members), BATCH_SIZE)]

    rprint(f"[bold blue]Coder:[/] {total} members → "
           f"{len(batches)} batch call(s) + {len(retry_members)} individual retry call(s)")

    # ---- Collect batch Ruby blocks ----
    batch_ruby_parts: list[str] = []
    for b_idx, batch in enumerate(batches, 1):
        marks = [m.get("mark", "?") for m in batch]
        rprint(f"  Batch {b_idx}/{len(batches)}: {len(batch)} members ({marks[0]} … {marks[-1]})")
        batch_ruby = _generate_ruby_for_batch(batch)
        batch_ruby_parts.append(batch_ruby)

    # ---- Collect retry Ruby blocks ----
    retry_ruby_parts: list[tuple[str, dict]] = []
    for member in retry_members:
        mark = member.get("mark", "?")
        rprint(f"  Retry: {mark}")
        feedback = error_feedback_map[mark]
        ruby_block = generate_ruby_for_member(member, feedback, None)
        retry_ruby_parts.append((mark, member, ruby_block))

    # ---- Assemble final script ----
    blocks = [RUBY_HEADER]

    for part in batch_ruby_parts:
        blocks.append(part)

    for mark, member, ruby_block in retry_ruby_parts:
        blocks.append(
            f"\n# ---- {mark} | {member.get('section','')} | {member.get('type','')} ----\n"
            f"{ruby_block}\n"
        )

    blocks.append(RUBY_FOOTER)
    return "\n".join(blocks)


def save_ruby_script(script: str) -> None:
    Path(CODER_OUTPUT_FILE).parent.mkdir(parents=True, exist_ok=True)
    with open(CODER_OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(script)
    rprint(f"\n[bold green]Coder complete.[/] Ruby script → {CODER_OUTPUT_FILE}")


if __name__ == "__main__":
    with open(MAPPED_OUTPUT_FILE, "r", encoding="utf-8") as f:
        data = json.load(f)
    members = data.get("mapped_members", [])
    script = build_ruby_script(members)
    save_ruby_script(script)
