"""
Agent 5 — Ruby Coder (upgraded)
Phase 5: Generate LOD 300 SketchUp Ruby script from 3D-mapped members.

For each member with start_point + end_point + rotation_degrees:
  1. Compute extrusion vector
  2. Build cross-section face on a plane perpendicular to the vector
  3. Rotate face by rotation_degrees
  4. PushPull by member length
  5. Tag with IFC attributes + correct layer

Unmapped members (confidence="unmapped") go to layer LOD300_UNMAPPED_NEEDS_REVIEW.
"""

import json
from pathlib import Path
from rich import print as rprint

from config import MAPPED_OUTPUT_FILE, CODER_OUTPUT_FILE
from core.llm_wrapper import call_llm, call_llm_with_feedback


# Source: AS/NZS 3679.1 & AS/NZS 1163 section tables
AUSTRALIAN_STEEL_SECTIONS: dict[str, dict] = {
    # ── UB — Universal Beam (old Australian format) ──────────────────────────
    "UB36b": {"type": "UB", "d": 359, "bf": 172, "tf": 13.0, "tw": 8.0},
    "UB36a": {"type": "UB", "d": 356, "bf": 171, "tf": 11.5, "tw": 7.0},
    "UB30a": {"type": "UB", "d": 303, "bf": 165, "tf":  9.9, "tw": 6.1},
    "UB25b": {"type": "UB", "d": 256, "bf": 146, "tf": 10.9, "tw": 6.4},
    "UB25a": {"type": "UB", "d": 254, "bf": 146, "tf":  8.6, "tw": 5.8},
    "UB20b": {"type": "UB", "d": 206, "bf": 133, "tf":  9.6, "tw": 6.2},
    "UB20a": {"type": "UB", "d": 203, "bf": 133, "tf":  7.8, "tw": 5.8},
    "UB15a": {"type": "UB", "d": 155, "bf": 102, "tf":  7.0, "tw": 4.5},
    # ── UB — Universal Beam (metric format) ──────────────────────────────────
    "360UB56.7": {"type": "UB", "d": 359, "bf": 172, "tf": 13.0, "tw": 8.0},
    "310UB40.4": {"type": "UB", "d": 304, "bf": 165, "tf":  8.7, "tw": 6.1},
    "250UB37.3": {"type": "UB", "d": 256, "bf": 146, "tf": 10.9, "tw": 6.4},
    "200UB29.8": {"type": "UB", "d": 207, "bf": 134, "tf":  9.6, "tw": 6.3},
    "150UB18.0": {"type": "UB", "d": 155, "bf": 102, "tf":  7.0, "tw": 4.5},
    # ── UC — Universal Column (old format) ───────────────────────────────────
    "UC155d": {"type": "UC", "d": 158, "bf": 153, "tf": 10.0, "tw": 6.6},
    "UC155c": {"type": "UC", "d": 152, "bf": 152, "tf":  8.0, "tw": 5.0},
    "UC100a": {"type": "UC", "d":  97, "bf":  99, "tf":  7.8, "tw": 4.6},
    # ── UC — Universal Column (metric format) ────────────────────────────────
    "150UC30.0": {"type": "UC", "d": 158, "bf": 153, "tf": 10.0, "tw": 6.6},
    "100UC14.8": {"type": "UC", "d":  97, "bf":  99, "tf":  7.8, "tw": 4.6},
    # ── PFC — Parallel Flange Channel (old CH format) ────────────────────────
    "CH35a": {"type": "PFC", "d": 380, "bf": 100, "tf": 17.5, "tw": 10.0},
    "CH35b": {"type": "PFC", "d": 380, "bf": 100, "tf": 17.5, "tw": 10.0},
    "CH30a": {"type": "PFC", "d": 310, "bf":  86, "tf": 14.8, "tw":  9.1},
    "CH13c": {"type": "PFC", "d": 125, "bf":  65, "tf":  9.5, "tw":  6.5},
    "CH40b": {"type": "PFC", "d": 430, "bf": 100, "tf": 19.0, "tw": 11.5},
    # ── PFC — Parallel Flange Channel (metric format) ────────────────────────
    "380PFC": {"type": "PFC", "d": 380, "bf": 100, "tf": 17.5, "tw": 10.0},
    "310PFC": {"type": "PFC", "d": 310, "bf":  86, "tf": 14.8, "tw":  9.1},
    "125PFC": {"type": "PFC", "d": 125, "bf":  65, "tf":  9.5, "tw":  6.5},
    # ── RHS / SHS — Rectangular / Square Hollow Section ─────────────────────
    "SH30b":      {"type": "RHS", "d": 300, "b": 100, "t": 6.0},
    "SH20a":      {"type": "RHS", "d": 200, "b":  75, "t": 4.0},
    "SH08d":      {"type": "SHS", "d":  89, "b":  89, "t": 3.5},
    "SH07g":      {"type": "SHS", "d":  75, "b":  75, "t": 3.0},
    "SH07f":      {"type": "SHS", "d":  75, "b":  75, "t": 2.5},
    "150x50x5RHS": {"type": "RHS", "d": 150, "b":  50, "t": 5.0},
    "100x50x4RHS": {"type": "RHS", "d": 100, "b":  50, "t": 4.0},
    # ── FB — Flat Bar (dimensions must come from drawing callout) ────────────
    "FB": {"type": "FB", "d": None, "b": None, "t": None},
}


def lookup_section(section_str: str) -> dict | None:
    """
    Look up a section designation in AUSTRALIAN_STEEL_SECTIONS.
    Returns the dims dict if found, else None.
    """
    if not section_str:
        return None
    key = section_str.strip()
    result = AUSTRALIAN_STEEL_SECTIONS.get(key)
    if result is not None:
        return result
    # Try stripping trailing dots or extra whitespace variants
    key2 = key.rstrip(".")
    return AUSTRALIAN_STEEL_SECTIONS.get(key2)


RUBY_HEADER = """\
# =============================================================================
# LOD 300 Structural Model — Auto-Generated by PDF-to-SketchUp Pipeline
# Model: gemini-2.5-flash  |  DO NOT EDIT — regenerate from mapped_members.json
# =============================================================================

model  = Sketchup.active_model
model.name        = "LOD300 Structural Model"
model.description = "Generated by PDF-to-SketchUp pipeline"
ents   = model.active_entities
layers = model.layers
model.start_operation('LOD300 Structural Import', true)

def get_or_create_layer(layers, name)
  layers[name] || layers.add(name)
end

"""

RUBY_FOOTER = """\

model.commit_operation
puts "=== LOD 300 Import Complete ==="

# Auto-save model as .skp alongside this script
_skp_path = File.expand_path(File.join(File.dirname(__FILE__), 'lod300_model.skp'))
_saved = Sketchup.active_model.save(_skp_path)
puts _saved ? "Model saved: #{_skp_path}" : "Save FAILED: #{_skp_path}"
"""


CODER_PROMPT = """You are an Expert SketchUp Ruby API Developer generating LOD 300 structural elements.

Australian steel section lookup is pre-loaded — when you see old-format designations like UB36b, UC155d, CH35a, use these exact dimensions:
{section_lookup_hint}

Member data (JSON):
{member_json}

Write Ruby code that PRECISELY places this member in 3D space.

STRICT RULES — follow every one or the script will fail:
1. All dimensions in SketchUp inches. Convert mm with `.mm` suffix (e.g. `6000.mm`).
2. Compute start and end:
   start_pt = Geom::Point3d.new({sx}.mm, {sy}.mm, {sz}.mm)
   end_pt   = Geom::Point3d.new({ex}.mm, {ey}.mm, {ez}.mm)
3. Extrusion vector:
   vec = start_pt.vector_to(end_pt)
   length = start_pt.distance(end_pt)
4. Create a local group:
   grp = ents.add_group
   g_ents = grp.entities
5. Build the 2D cross-section face AT start_pt on a plane NORMAL to `vec`:
   - I/UB/UC sections: draw top flange, web, bottom flange as one closed polygon.
     Use actual flange width (bf), web height (d - 2*tf), flange thickness (tf), web thickness (tw).
     Parse these from the section string. If unknown, use proportional defaults:
     d = section_depth, bf = d*0.5, tf = d*0.06, tw = d*0.03.
   - RHS/SHS: outer rect minus inner rect (draw solid, SketchUp will show as box; note hollow).
   - CHS: 24-sided polygon approximation using Math::PI and radius.
   - PL/FB: simple rectangle (width x thickness).
   Use `Geom::Transformation.new` with a local coordinate system aligned to `vec`.
   Transform face points into world space before drawing.
6. Get the face: `face = g_ents.grep(Sketchup::Face).first`
7. Extrude: `face.pushpull(length)` (SketchUp's pushpull takes internal units — already in inches from step 1+3).
8. Layer assignment:
   layer_name = {layer_name}
   grp.layer = get_or_create_layer(layers, layer_name)
9. IFC attributes:
   grp.set_attribute("IFC", "Mark",    "{mark}")
   grp.set_attribute("IFC", "Section", "{section}")
   grp.set_attribute("IFC", "Type",    "{type}")
10. Name the group: `grp.name = "{mark}"`

Output ONLY valid Ruby code. No markdown, no prose, no method definitions outside the snippet."""


BATCH_CODER_PROMPT = """You are an Expert SketchUp Ruby API Developer.
Generate SketchUp Ruby API code to place {count} structural members in 3D space.

IMPORTANT — OUTPUT FORMAT:
- Output ONLY executable Ruby code. No markdown, no prose, no explanations.
- Do NOT define any constants or variables for the input data.
- Do NOT echo back or embed the JSON data in your output.
- For EACH member, output Ruby code that calls SketchUp API methods directly.

OUTER SCOPE variables already defined (DO NOT redefine them):
  model, ents, layers, get_or_create_layer

MEMBER DATA:
{members_json}

FOR EACH MEMBER, generate Ruby code in this EXACT pattern:

# ---- <MARK> | <SECTION> | <TYPE> ----
begin
  _sp  = Geom::Point3d.new(<start_x>.mm, <start_y>.mm, <start_z>.mm)
  _ep  = Geom::Point3d.new(<end_x>.mm,   <end_y>.mm,   <end_z>.mm)
  _vec = _sp.vector_to(_ep)
  _len = _sp.distance(_ep)
  _grp = ents.add_group
  _ge  = _grp.entities
  _t   = Geom::Transformation.new(_sp, _vec)
  # Cross-section at origin, extruded along _vec
  # I/UB/UC: bf=<bf>mm, d=<d>mm, tf=<tf>mm, tw=<tw>mm
  _pts = [<2D cross-section points in LOCAL coords, mm units>]
  _face = _ge.add_face(_pts.map { |p| _t * Geom::Point3d.new(p[0].mm, p[1].mm, 0) })
  _face.pushpull(_len)
  _grp.layer = get_or_create_layer(layers, "<LAYER_NAME>")
  _grp.set_attribute("IFC", "Mark",    "<MARK>")
  _grp.set_attribute("IFC", "Section", "<SECTION>")
  _grp.set_attribute("IFC", "Type",    "<TYPE>")
  _grp.name = "<MARK>"
rescue => e
  puts "SKIP <MARK>: #{e.message}"
end

CROSS-SECTION RULES:
- I/UB/UC section (bf, d, tf, tw known): draw H-shape polygon:
  half_bf = bf/2; half_tw = tw/2; web_h = d - 2*tf
  points (clockwise from bottom-left of bottom flange):
  [-half_bf,0], [half_bf,0], [half_bf,tf], [half_tw,tf],
  [half_tw,tf+web_h], [half_bf,tf+web_h], [half_bf,d], [-half_bf,d],
  [-half_bf,tf+web_h], [-half_tw,tf+web_h], [-half_tw,tf], [-half_bf,tf]

- PFC/Channel (bf, d, tf, tw known): draw C-shape polygon:
  points: [0,0],[bf,0],[bf,tf],[tw,tf],[tw,d-tf],[bf,d-tf],[bf,d],[0,d]

- RHS/SHS (b, d, t known): solid rectangle (b x d):
  points: [0,0],[b,0],[b,d],[0,d]

- CHS (outer_radius r, thickness t): 24-sided polygon approximation:
  (1..24).map { |i| a = 2*Math::PI*i/24; [r*Math::cos(a), r*Math::sin(a)] }

- PL/FB (width w, thickness t): rectangle [0,0],[w,0],[w,t],[0,t]

- UNKNOWN section: use rectangle 100mm x 100mm as placeholder

LAYER NAME RULES:
- confidence == "unmapped" OR start_z == -9999 OR end_z == -9999:
    layer = "LOD300_UNMAPPED_NEEDS_REVIEW"
    AND override start_pt = (0,0,0), end_pt = (0,0,3000) so it doesn't crash
- type == "beam"   → "LOD300_BEAM"
- type == "column" → "LOD300_COLUMN"
- type == "slab"   → "LOD300_SLAB"
- type == "brace"  → "LOD300_BRACE"
- type == "wall"   → "LOD300_WALL"
- other            → "LOD300_OTHER"

Generate code for ALL {count} members. Output ONLY Ruby code."""


def _fill_prompt(member: dict) -> str:
    sp      = member.get("start_point") or {"x": 0, "y": 0, "z": 0}
    ep      = member.get("end_point")   or {"x": 0, "y": 0, "z": 3000}
    mark    = member.get("mark")    or "M?"
    section = member.get("section") or "UB200x100x20"
    mtype   = member.get("type")    or "beam"
    conf    = member.get("confidence") or "high"
    layer_name = (
        "LOD300_UNMAPPED_NEEDS_REVIEW" if conf == "unmapped"
        else f"LOD300_{mtype.upper()}"
    )

    sx = str(sp.get("x") or 0); sy = str(sp.get("y") or 0); sz = str(sp.get("z") or 0)
    ex = str(ep.get("x") or 0); ey = str(ep.get("y") or 0); ez = str(ep.get("z") or 3000)

    dims = member.get("_section_dims")
    hint = json.dumps(dims, indent=2) if dims else "(not in lookup table — infer from section string)"

    return (
        CODER_PROMPT
        .replace("{member_json}", json.dumps(member, indent=2))
        .replace("{section_lookup_hint}", hint)
        .replace("{sx}", sx).replace("{sy}", sy).replace("{sz}", sz)
        .replace("{ex}", ex).replace("{ey}", ey).replace("{ez}", ez)
        .replace("{layer_name}", f'"{layer_name}"')
        .replace("{mark}", mark)
        .replace("{section}", section)
        .replace("{type}", mtype)
    )


def _fill_batch_prompt(batch: list[dict]) -> str:
    return (
        BATCH_CODER_PROMPT
        .replace("{count}", str(len(batch)))
        .replace("{members_json}", json.dumps(batch, indent=2))
    )


def generate_ruby_for_member(member: dict, error_feedback: str | None = None, previous_ruby: str | None = None) -> str:
    """Single-member call — used only for error-feedback retries."""
    if error_feedback:
        base = _fill_batch_prompt([member])
        prompt = (
            base
            + "\n\n--- AUDITOR FEEDBACK (fix these issues) ---\n"
            + error_feedback
            + "\n\nOutput ONLY corrected Ruby code using the begin/rescue pattern shown above."
        )
        raw = call_llm(prompt)
    else:
        raw = _generate_ruby_for_batch([member])
    raw = raw.strip()
    if raw.startswith("```"):
        raw = raw.split("```", 1)[1]
        if raw.startswith("ruby"):
            raw = raw[4:]
        raw = raw.rsplit("```", 1)[0].strip()
    return raw


def _generate_ruby_for_batch(batch: list[dict]) -> str:
    """Send one batch of members to the LLM, return raw Ruby text for the whole batch."""
    prompt = _fill_batch_prompt(batch)
    raw = call_llm(prompt)
    # Strip accidental markdown fences
    raw = raw.strip()
    if raw.startswith("```"):
        raw = raw.split("```", 1)[1]
        if raw.startswith("ruby"):
            raw = raw[4:]
        raw = raw.rsplit("```", 1)[0].strip()
    return raw


def build_ruby_script(mapped_members: list[dict], error_feedback_map: dict | None = None) -> str:
    """
    Build the full Ruby script using at most 3 batched LLM calls.
    error_feedback_map retries are still done per-member (single call) to keep diffs minimal.
    """
    error_feedback_map = error_feedback_map or {}
    total = len(mapped_members)

    # ── Section lookup: inject _section_dims before any LLM call ─────────────
    hit_count = 0
    for member in mapped_members:
        dims = lookup_section(member.get("section", ""))
        if dims is not None:
            member["_section_dims"] = dims
            hit_count += 1
    rprint(f"  Section lookup: {hit_count}/{total} members resolved from table (no API needed)")

    # Split members needing error-retry out first; they get individual calls.
    retry_members  = [m for m in mapped_members if error_feedback_map.get(m.get("mark", ""))]
    batch_members  = [m for m in mapped_members if not error_feedback_map.get(m.get("mark", ""))]

    BATCH_SIZE = 8
    batches = [batch_members[i:i + BATCH_SIZE] for i in range(0, len(batch_members), BATCH_SIZE)]

    rprint(f"[bold blue]Coder:[/] {total} members → "
           f"{len(batches)} batch call(s) + {len(retry_members)} individual retry call(s)")

    # ---- Collect batch Ruby blocks ----
    batch_ruby_parts: list[str] = []
    for b_idx, batch in enumerate(batches, 1):
        marks = [m.get("mark", "?") for m in batch]
        rprint(f"  Batch {b_idx}/{len(batches)}: {len(batch)} members ({marks[0]} … {marks[-1]})")
        batch_ruby = _generate_ruby_for_batch(batch)
        batch_ruby_parts.append(batch_ruby)

    # ---- Collect retry Ruby blocks ----
    retry_ruby_parts: list[tuple[str, dict]] = []
    for member in retry_members:
        mark = member.get("mark", "?")
        rprint(f"  Retry: {mark}")
        feedback = error_feedback_map[mark]
        ruby_block = generate_ruby_for_member(member, feedback, None)
        ruby_block = ruby_block.strip()
        if ruby_block.startswith("```"):
            ruby_block = ruby_block.split("```", 1)[1]
            if ruby_block.startswith("ruby"):
                ruby_block = ruby_block[4:]
            ruby_block = ruby_block.rsplit("```", 1)[0].strip()
        retry_ruby_parts.append((mark, member, ruby_block))

    # ---- Assemble final script ----
    blocks = [RUBY_HEADER]

    for part in batch_ruby_parts:
        blocks.append(part)

    for mark, member, ruby_block in retry_ruby_parts:
        blocks.append(
            f"\n# ---- {mark} | {member.get('section','')} | {member.get('type','')} ----\n"
            f"{ruby_block}\n"
        )

    blocks.append(RUBY_FOOTER)
    return "\n".join(blocks)


def save_ruby_script(script: str) -> None:
    Path(CODER_OUTPUT_FILE).parent.mkdir(parents=True, exist_ok=True)
    with open(CODER_OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(script)
    rprint(f"\n[bold green]Coder complete.[/] Ruby script → {CODER_OUTPUT_FILE}")


if __name__ == "__main__":
    with open(MAPPED_OUTPUT_FILE, "r", encoding="utf-8") as f:
        data = json.load(f)
    members = data.get("mapped_members", [])
    script = build_ruby_script(members)
    save_ruby_script(script)
